### ISSUE TITLE
Sometimes there is a slowness in the servers.. Is there a solution for this like adding a cache feature?

### ISSUE THREAD

**Issue by ibraelmahallawy** [vipulyaara/Kafka#36]
Sometimes there is a slowness in the servers.. Is there a solution for this like adding a cache feature?

**Comment by vipulyaara** [comment]
Could you please elaborate on what kind of slowness? While opening book details, opening reader, downloading a book, or playing music for example?

**Comment by vipulyaara** [comment]
@ibraelmahallawy could you please update?

**Comment by ibraelmahallawy** [comment]
It seems that the problem was with my internet speed.. It is now working great.

**Comment by vipulyaara** [comment]
Okay. Archive servers can be slow sometimes but usually it's fine to work with.
