### ISSUE TITLE
Is it possible to designate specific accounts to fetch books from

### ISSUE THREAD

**Issue by ibraelmahallawy** [vipulyaara/Kafka#40]
Is it possible to designate specific accounts to fetch books from, whether they are ebooks or audiobooks?

**Comment by vipulyaara** [comment]
I am not sure what you mean. Do you need a way to search for books by uploader name/account?

**Comment by ibraelmahallawy** [comment]
Do you need a way to search for books by uploader name/account?
Yes, Is this possible?

**Comment by vipulyaara** [comment]
I don't think it is possible. Furthermore, this will not be useful, as a typical user does not know the name of the file’s uploader. You can search by Creator (author) name if that helps.
