### ISSUE TITLE
Could not HEAD 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.2.0-beta.1/android-pdf-viewer-3.2.0-beta.1.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by William45-coder** [vipulyaara/Kafka#42]
When building the project, this error appears.. 

Could not HEAD 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.2.0-beta.1/android-pdf-viewer-3.2.0-beta.1.pom'. Received status code 401 from server: Unauthorized

How can I solve this problem please?

**Comment by vipulyaara** [comment]
I just checked out the project in a new directory and it worked fine. Maybe this thread can help https://github.com/DImuthuUpe/AndroidPdfViewer/issues/1206

**Comment by vipulyaara** [comment]
I can reproduce it after clearing the system-wide gradle cache. It's fixed in the new commit on `develop`. Everything should work now.

**Comment by William45-coder** [comment]
Now the code is working.. Thank you.. I have one last question.. How do you control the books and categories that appear on the homepage?

**Comment by vipulyaara** [comment]
The homepage is maintained on a CMS on Firebase. It can be configured differently for each country.

**Comment by William45-coder** [comment]
Can you share how to set that up?
If possible.

**Comment by vipulyaara** [comment]
Please contact me on Twitter @vipulyaara if it's going to be a longer discussion.

**Comment by vipulyaara** [comment]
Homepage is built using a combination of manually curated items and algorithms for user recommendations and trending content based on user analytics. You can set up a [Firebase](https://firebase.google.com/) project with a Firestore collection called `homepage` and host these items (for manually curated content). The item schema can be found in the file `HomepageResponse`.

Out of curiosity, why do you want to host your own homepage?

**Comment by William45-coder** [comment]
I'm a beginner in the field, and I was working on a project for a movies and series app using TheMovieDB API. I wanted to understand how to create a homepage that I can control without the need to create a dedicated dashboard.

**Comment by vipulyaara** [comment]
Then you probably don't need a homepage like Kafka. I suggest you look at [TiVi](https://github.com/chrisbanes/tivi). It uses Trakt and TMDB to fetch movies and TV shows, exactly the same use case as yours.

If you still want a manually curated homepage, try some tutorials on Firebase or other backend services. Firebase has GUI so it's easy to edit for non-technical people.

**Comment by William45-coder** [comment]
Thank you very much. I think this nomination is very appropriate.
