### ISSUE TITLE
The app is not working

### ISSUE THREAD

**Issue by ibraelmahallawy** [vipulyaara/Kafka#46]
![Screenshot_2024-10-10-01-42-12-290_com kafka user](https://github.com/user-attachments/assets/277ee1da-d2cb-4946-be84-2dd361a0f0d9)

The app is not working.

**Comment by vipulyaara** [comment]
The Internet Archive servers were down yesterday. We are planning to move the content, starting with homepage, on our own servers which should make everything load faster.

**Comment by vipulyaara** [comment]
Internet Archive was hacked yesterday so the servers are down. Hoping it will be restored soon.

**Comment by vipulyaara** [comment]
It's working now
