### ISSUE TITLE
Tab clicks don't work after switching tabs programatically

### ISSUE THREAD

**Issue by vipulyaara** [vipulyaara/Kafka#5]
Steps to reproduce:
- Click on a creator name in item detail from `Home` tab
- User is taken to `Search` tab
- Click on `Home` tab

Expected:
Home page is shown

Actual:
Nothing happens

**Comment by AbhinavSingh111** [comment]
this issue no longer persist. Not able to recreate.

**Comment by vipulyaara** [comment]
Fixed
