### ISSUE TITLE
Login ability for Internet Archive

### ISSUE THREAD

**Issue by ArchCelestial** [vipulyaara/Kafka#54]
Some books are locked behind logging into Internet Archive. The ability to login to internet archive and then being able to access the books would be nice.

**Comment by vipulyaara** [comment]
You can click on "Borrow" from the detail page and it opens the archive website. You need to log in there once and the app will keep your session. Borrowing works after that.

**Comment by ArchCelestial** [comment]
Do I have to go into the website first, then borrow it there, then check the app?

**Comment by vipulyaara** [comment]
Here's a video tutorial. Let me know if you have further questions.

https://github.com/user-attachments/assets/6a5c34ef-11fa-4e7d-9881-3714c5239476

**Comment by ArchCelestial** [comment]
There is a book I was trying to to read through the app, called "Joshua, a parable for today." That doesn't show up in the app, however I am able to read it on the website.

**Comment by vipulyaara** [comment]
Can you send me the link to the book on archive website? I can't find a book by this name on website.

**Comment by ArchCelestial** [comment]
https://archive.org/details/joshua0000girz

I am able to see it after I login to the website

**Comment by vipulyaara** [comment]
I see. This item seems to have issue in search. For example, if you click on the author on website, this book doesn't show up under their works on [search page](https://archive.org/search?query=Joshua,+Girzone,+Joseph+F).

One trick would be to create an app URL from archive item. For example [archive.org/details/joshua0000girz](https://archive.org/details/joshua0000girz) will become [www.kafkaarchives.org/item/joshua0000girz](www.kafkaarchives.org/item/joshua0000girz). Now if you click on this link from your phone, it should open in Kafka app.

**Comment by ArchCelestial** [comment]
It opens up the app, but doesn't go into the book.

**Comment by vipulyaara** [comment]
For me, it goes inside but the book is unavailable to borrow. Same message on the website.

<img height="500" alt="Screenshot 2024-11-28 at 7 16 32 PM" src="https://github.com/user-attachments/assets/b6dcb726-3a44-4662-9def-d36135bd699c">
<img width="1728" alt="Screenshot 2024-11-28 at 7 16 32 PM" src="https://github.com/user-attachments/assets/b84bdffd-dc8f-4933-9c59-f21f96b50e98">

**Comment by ArchCelestial** [comment]
I think I know why now, I signed up for the print disability service so that way all the books would become open to read. That could probably be why the borrow is unavailable.
